# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a56ba23d4b096689323300d94b403427b9cbcc127a17eca08c62279ae02f0de87d0e7d7b7b1c3fc0a0dc669b33927057a9c3191c2f50929e64546fb6d7d5135

test:
  secret_key_base: 9187d3a655f6d67a92f77e2d3c27b298c4265ff14bbf584e8d89c6a3137a1251c199cc651f5530a8cc69f997ec898a45fa5760d4e8307c1db15b0d5d30465922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
